### ISSUE TITLE
Error while climbing stairs

### ISSUE THREAD

**Issue by ChrisLeick** [Noodlemire/VoxelDungeon#3]
AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback luaentity_Step(): /usr/share/games/minetest/builtin/common/vector.lua:44: attempt to index local 'v' (a nil value)
stack traceback:
	/usr/share/games/minetest/builtin/common/vector.lua:44: in function 'round'
	....minetest/games/voxeldungeon/mods/voxeldungeon/blobs.lua:205: in function 'get'
	....minetest/games/voxeldungeon/mods/voxeldungeon/items.lua:247: in function <....minetest/games/voxeldungeon/mods/voxeldungeon/items.lua:244>

**Comment by Noodlemire** [comment]
Fixed as of 1.6.1. Though it was random, and not stair-related.
